notifications:
  email:
    on_success: never
    on_failure: change

osx_image: xcode7.3

dist: trusty
sudo: false

language: c

env:
  global:
    - ELECTRON_CACHE=$HOME/.electron
    - secure: psJxnBOQ+k47FV0X20MRwIcEtnfVhyExPJ4Ku7RXIDvyhFbHDMQe7T351KAjMOxR/cjBWuZD9rcxcDi4XKK2ZvXBzRPzNRzDs9Gnrk+n6IkSUIS0utBfWryjRkAQAbXTXAKdmrgS1YcIjFOkGKOWehVn/OpcCwq6B9joWqY00ZI+2Ut7MdEonHN/Ki22rhM+FeUW1w6/ZDYRI6sImcim0Dz0nleXizddhhv+/WJHxpLkzeXOErUnlHRRuhHIgeXWd+Gq68gKowgt4ZqckV7HhomNwwF4ck17y1PQk6ObDZh6dvHIhlvsb+5dtYf/imSMnj9hGq56nZ5H07P9qSgn55oBJCtiT1uR4sieatUVe8sv+dWHqKN+alZD6SRf/PYcgDc2DY35Wv8aUuQZmLf68Knt9o1oAOWFRtkVHkJlVAa+kwuBjv16GIWz3J0whvNexC8dEl+5EW402S33fv+34nuLttIY7ig97n9b+RStpf6PBfo+L3uuqH4BfTpDF98ZQgwbA7Oy596tuT2gYVDOgpSABEtzELmn0gDFaWtC+EGOnv/3wVtml7BBeIkQORWnQBVFI2f/EgKZ2jnqMJE9j1m9uRHLuD4TnpNdsGYK/41XDWaXJl0ZU+q27KJQdfkXAUVBmX9XDfIoNzyzGSVqsf8C+S6pdbOZ50A0pb3yKfo=

matrix:
  fast_finish: true
  include:
    - os: osx

    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - ./app/node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/git-lfs/git-lfs/releases/download/v2.1.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.1.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
- nvm install 7
- yarn install
- yarn add electron-builder@next --dev # force install next version to test electron-builder

script:
  - yarn run test
  - yarn run release

