notifications:
  email:
    on_success: never
    on_failure: change

osx_image: xcode7.3

dist: trusty
sudo: false

language: c

env:
  global:
    - ELECTRON_CACHE=$HOME/.electron
    - secure: SVM9ic8HxELwbzbQoTC6n0vWk7qDNUGyujaczpvX/suqsXaTkie00t7xU9Iod2JknJZAcuowejJQTB94uvl52TqZlb7xZFGWpXeYf2QKMO+wS5jwxfBKOVMrSVZhNmEnv94T0JD2XHKiIWxi17jVv8rWzuivdmD6L641W+QVdOV4c45ODiNLwApbiypPgIC3ZAy8CSGmQ0UTgxzJ5chLW2cQKw5/A9u2pCIBaQmDDQ6u6WCDrMVrH51vwgAFqjLKIKIBJ7sczb5ARzUyFEEsB87XFVGslkLP6/t44qlmbhTXNN+Oe/DAoEv1Ul0e5HVRNwMP0R1OMYKMmwThp2FgzQ2AhkisdfMr36z3p8DCoof8j1LcDBNRWHjS7fHuuheNw0ep4aCy8hbEXDBwDFnMlTZr5tU44bfoUwfUIMhcb81Pj3zpBDmpyAgN0vUdDulnP5L/ZTL8rgIffzGri9ARawZn/hi11GFxzKrFQaEyCNqOg7RVV+CWRXL1rTkEXw0taVE9CMLydM9vMSfTfzTa1/G6XRVfYqPBdlQqOBb8/UHDlh8Hrhug7uiLKMfmy2RNsWNwHPBtKbKRXoGQeOI8UdxWEG3HBZzubeNNX3KSp/WG4kSkxx2+dZWKkSN5F48znKhWyZGYBYmyJ85TUHcwDFY71JRlTvG/bAia1Re07eE=

matrix:
  fast_finish: true
  include:
    - os: osx

    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - ./app/node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/git-lfs/git-lfs/releases/download/v2.1.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.1.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
- nvm install 7
- yarn install
- yarn add electron-builder@next --dev # force install next version to test electron-builder

script:
  - yarn run test
  - yarn run release

