notifications:
  email:
    on_success: never
    on_failure: change

osx_image: xcode7.3

dist: trusty
sudo: false

language: c

env:
  global:
    - ELECTRON_CACHE=$HOME/.electron
    - secure: ZQ/ik87X609978YGmjZU5/Cv9qe9BZKiQ4Tkyjk0EHi8wSz7JcJN/LCR71NkY4AsqqIY83qYnKivXU9xoXilzdSuRRk7HYErKR5l049WMci/7wGiXK9WWz3MIKQsWGk/26VpmFTlS4FOUTQHfpm7yR+l0rNEotd9rY6JpsLMrS+2J3autFcs0CihPQ064C+PnyPDxbACdOZW11MAccbe8HJ4d6uVP0nRdkNs0tj3ZyIBJmYoC8syfjpxsMDnxcXihOoHx8zt/gWv7H4YQ03D/1nGUC2tupDL/ErH0ykZQaPeyLAwEN+GQgJpYvMpkdKOU+u8JuuMtXjCLWttFOhKF8JjHXHlxGcF8d58wY+r7+ZNTz6tfcVhEbSyORkOaKzasQ4cXDlW7c5h2ImrM5ttgh4OljVZ904jqSDHG8L1R6znXOsh3CSH96DGNtleCl8QhB/Sz1zpTwt2djHvB7Q+GY6c/tVb6qPy/FJCwg925OP3p8oYtYfqhqT2ZUZr1/Vh9Y3OkRMpsj6UagMu5CgTg8OC2eWrNyVi9VVh92qM7QeWXTDf/rCPEM7XCFoATsgFpmR4ougxHj3ULstRWaP+vCiodaZot2KvJ+uwoWB2aWum8sm2TEbPEzlSQ8U8fPtDZpy8mh1IHQ8t6F9xORwuzg1cNGvu9qjVBlVSqWs5x9g=

matrix:
  fast_finish: true
  include:
    - os: osx

    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - ./app/node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/git-lfs/git-lfs/releases/download/v2.1.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.1.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
- nvm install 7
- yarn install
- yarn add electron-builder@next --dev # force install next version to test electron-builder

script:
  - yarn run test
  - yarn run release

