os: osx
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
env:
  - isRelease=[[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]]
before_install:
  - 'if [ "$isRelease" = "true" ]; then
      brew update;
      brew install wine;
      brew install mono;
      brew install gnu-tar graphicsmagick xz;
     fi'
before_script:
  - node -v
  - npm -v
  - nvm version
  - npm prune
  - echo $isRelease
after_success:
  - 'if [ "$isRelease" = "true" ]; then
      npm run semantic-release;
     fi'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
