notifications:
  email:
    on_success: never
    on_failure: change

osx_image: xcode7.3

dist: trusty
sudo: false

language: c

env:
  global:
    - ELECTRON_CACHE=$HOME/.electron
    - secure: MgcRXeOmgwzWjYn0XH7DrClRk1TY8E0r16luPYpXkTGpD7KQAEJ0bfAa4Igs4JNqVng5EFx12Z3Z07H1u6GG8QOX3qfEVS5pUXmjrDuLDUHbevz46C8l46pmp7qCZRj5H65Qq5mKJMPCMn0W0z3yoRiWvuEwC42Nr6nM8l9OpRvDlreVukKXQqY8lChBRLCPxHtJrWGCyH9gNgc85OaRW8Od2aNhqkA3H+i8GAKrcisItM5yKs14PJGtm6F81Ue/U5/WTN+OsHmChT2H9hSR/d1Cs4gyMkfpXELclY6x40+POsSDX9pFilhKUAJqonHZnhpoTSqhOVuy8jY+D0PNwcEqlg8YD5a6vzig+/z2t/egKMoh/FRikXV3Xxmp+KfgwYu3rODq7i49syvssr3xC0aOmOZ/nE+ScClJMkvjY6ygUIzALmQsdeywTECJT7AcQPPPrQYrRh/f2KG+pcTGdix0aEKc2J+En7cDY9roXip3bRtz4X5GoufDrLOecajHhBEk8Y4AiFVxT35o1HCZei/8/AcJ4kXEE5/hw9dzsGsDPqToQtP/i3d5kQRGAN5A4ORfckpm3qNNLQIVDhjzdamL8dhOuFfJx3Wviox0G0HXXf1sOyh5ywzN5bHLjTLaMlxMXYW5uUJ/VwGF2c2EMha+Je1DgGy91ZnQTfyEYXo=

matrix:
  fast_finish: true
  include:
    - os: osx

    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - ./app/node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/git-lfs/git-lfs/releases/download/v2.1.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.1.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
- nvm install 7
- yarn install
- yarn add electron-builder@next --dev # force install next version to test electron-builder

script:
  - yarn run test
  - yarn run release

