os: osx
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then brew update; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then brew install wine; fi'
before_script:
  - npm prune
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
