sudo: required
dist: trusty
os: osx
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_install:
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then
      brew update;
      brew install wine --without-x11;
      brew install mono;
      brew install gnu-tar graphicsmagick xz;
     fi'
before_script:
  - npm prune
after_success:
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then
      npm run semantic-release;
     fi'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
